---
apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  name: ocs-external-storagecluster-storagesystem
  namespace: openshift-storage
  finalizers:
  - storagesystem.odf.openshift.io
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: ocs-external-storagecluster
  namespace: openshift-storage
...
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  finalizers:
  - storagecluster.ocs.openshift.io
  name: ocs-external-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage:
    enable: true
  labelSelector: {}
  multiCloudGateway:
    reconcileStrategy: ignore
  managedResources:
    cephBlockPools: {}
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
...
